# Generated by Django 3.0.8 on 2020-08-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='url',
            field=models.CharField(default='hello', max_length=200, unique=True),
        ),
    ]
